// Prompt governance config v1.0.0
// Keep risk terms, lens policy, pose modes, and category-specific rules outside core prompt code.
window.PROMPT_GOVERNANCE = {
  antiPatterns: {
    bannedCameraLanguageIds: ['cl_movie', 'cl_travel'],
    bannedAngleIds: ['yang', 'huimou'],
    bannedPromptTerms: [
      'movie trailer',
      'blockbuster',
      'dramatic hero framing',
      'looking back over shoulder',
      'turn-back glance',
      'low angle upward shot',
      'low-angle',
      'perfect beauty',
      'beauty',
      'gorgeous',
      'glamorous',
      'flawless',
      'perfect skin',
      'porcelain skin',
      'model face',
      'influencer face',
      'luxury beauty',
      'fantasy beauty',
      'succubus queen',
      'succubus woman',
      'demon queen',
      'demon sovereign',
      'fantasy queen',
      'fantasy empress',
      'goddess face',
      'goddess aura',
      'immortal aesthetic',
      'xianxia heroine',
      'dark fantasy heroine',
      'magazine cover',
      'magazine beauty',
      'editorial realism',
      'character editorial realism',
      'premium fantasy editorial realism',
      'concept art quality',
      'character concept art',
      'fashion beauty portrait',
      'cat-eye',
      'fox-eye',
      'sharp winged eyeliner',
      'dark regal contour',
      'contouring',
      'heavy smoky eye',
      'extreme pose',
      'jumping',
      'spinning',
      'back-facing',
      'travel documentary',
      'vlog',
      'candid travel',
      'low-key dramatic',
      'ethereal atmosphere',
      'celestial mist',
      'arms overhead',
      'covering face',
      'oversized head',
      'chibi proportions',
      'looking upward',
      'looking upwards',
      'dramatic side profile',
      'side profile',
      'over-the-shoulder',
      'half-body close portrait',
      'waist-up portrait',
      'face-readable close framing',
      'beauty-camera framing',
    ],
  },
  replacements: [
    ['movie trailer camera language', 'controlled documentary camera framing'],
    ['fashion editorial camera language', 'controlled real-person environmental camera framing'],
    ['magazine cover camera language', 'real tourist documentary photography language'],
    ['blockbuster visual language', 'documentary photographic language'],
    ['blockbuster', 'documentary photographic quality'],
    ['vlog', 'location-based real-person photography'],
    ['dramatic hero framing', 'stable cinematic framing'],
    ['looking back over shoulder', 'gentle three-quarter pause with face still readable'],
    ['turn-back glance', 'calm paused glance with face still readable'],
    ['looking curious toward the side', 'gentle natural eye contact toward camera'],
    ['looking upwards thoughtfully', 'soft neutral gaze slightly above camera level'],
    ['looking upward', 'camera-level gaze with stable face orientation'],
    ['looking upwards', 'camera-level gaze with stable face orientation'],
    ['dramatic side profile', 'mild three-quarter face angle with stable facial geometry'],
    ['side profile', 'mild three-quarter face angle with stable facial geometry'],
    ['over-the-shoulder turn-back pose', 'mild body turn while face remains camera-level and structurally readable'],
    ['turning back over the shoulder', 'mild body turn while face remains directed toward camera'],
    ['low-angle hero shot', 'eye-level or natural chest-height shot'],
    ['heroic angle', 'stable eye-level camera angle'],
    ['forced-perspective hero shot', 'stable eye-level camera angle without forced perspective'],
    ['low angle upward shot', 'stable eye-level or slight three-quarter shot'],
    ['low-angle', 'stable eye-level'],
    ['half-body close portrait', 'medium three-quarter portrait with balanced body proportion'],
    ['half-body portrait from waist up', 'medium three-quarter portrait with balanced head-to-shoulder-to-torso proportion'],
    ['waist-up portrait', 'medium three-quarter body composition'],
    ['face-readable half-body', 'identity-readable three-quarter portrait without enlarging the head'],
    ['face-readable close framing', 'identity-readable medium framing without enlarging the head'],
    ['upper costume details', 'complete upper-body silhouette'],
    ['beauty-camera framing', 'real-person camera framing with natural body scale'],
    ['perfect beauty reconstruction', 'natural appearance'],
    ['perfect beauty', 'authentic real-person appearance'],
    ['perfect skin', 'natural skin texture with real imperfections'],
    ['flawless skin', 'natural skin texture with real imperfections'],
    ['flawless', 'natural'],
    ['porcelain skin', 'authentic human skin texture'],
    ['model face', 'authentic real-person appearance'],
    ['influencer face', 'authentic real-person appearance'],
    ['glamorous beauty', 'authentic real-person appearance'],
    ['gorgeous', 'authentic'],
    ['glamorous', 'refined'],
    ['luxury beauty enhancement', 'natural styling'],
    ['luxury beauty', 'natural styling'],
    ['fantasy beauty', 'real-person portrait in a fantasy environment'],
    ['succubus queen', 'uploaded real person in dark supernatural costume styling'],
    ['succubus woman', 'uploaded real person wearing dark supernatural costume styling'],
    ['demon queen', 'real woman inside a dark supernatural environment'],
    ['demon sovereign', 'real woman in dark supernatural royal styling'],
    ['fantasy queen', 'uploaded real person wearing fantasy-inspired royal costume styling'],
    ['fantasy empress', 'uploaded real person wearing fantasy-inspired royal costume styling'],
    ['goddess face', 'mythic environment styling, no facial redesign'],
    ['goddess aura', 'mythic atmosphere around the environment'],
    ['immortal aesthetic', 'xianxia-inspired environment, not facial styling'],
    ['dark fantasy heroine', 'real person inside a dark fantasy environment'],
    ['xianxia heroine', 'real person inside a xianxia-inspired environment'],
    ['goddess', 'mythic figure styling around the uploaded real person'],
    ['heroine', 'central real person'],
    ['celebrity', 'reference subject'],
    ['cat-eye liner reshaping', 'soft liner color following the original eye shape'],
    ['cat-eye', 'soft liner following the original eye shape'],
    ['fox-eye', 'soft liner following the original eye shape'],
    ['sharp winged eyeliner', 'soft eyeliner color only, no eye-shape-changing liner'],
    ['dark regal contour', 'surface-only shadow toning, no facial reshaping'],
    ['contouring', 'surface color toning only, no facial reshaping'],
    ['contour', 'surface color toning only'],
    ['blackened red smoky eyes', 'subtle dark red smoky makeup, surface-only'],
    ['heavy smoky eye', 'controlled smoky eye kept surface-only'],
    ['extreme pose', 'controlled pose'],
    ['jumping', 'grounded motion'],
    ['spinning', 'gentle movement'],
    ['back-facing', 'face-readable'],
    ['arms overhead', 'hands kept below eye level'],
    ['covering face', 'face unobstructed'],
    ['ethereal light', 'soft atmospheric light'],
    ['cinematic glow makeup', 'minimal real travel makeup'],
    ['outdoor cinematic glow makeup', 'minimal real outdoor travel makeup'],
    ['glow makeup', 'minimal real makeup'],
    ['camera-ready but realistic', 'unretouched and realistic'],
    ['camera-ready', 'unretouched'],
    ['softly defined brows and lashes', 'natural untouched eyebrows and eyelashes'],
    ['softly defined brows', 'natural untouched eyebrows'],
    ['defined brows and lashes', 'natural untouched eyebrows and eyelashes'],
    ['defined lashes', 'natural untouched eyelashes'],
    ['defined brows', 'natural untouched eyebrows'],
    ['healthy peach or rose lip', 'natural lip color matching the reference person'],
    ['healthy coral lip', 'natural lip color matching the reference person'],
    ['premium world travel editorial realism', 'documentary world travel photo realism'],
    ['premium travel editorial realism', 'documentary travel photo realism'],
    ['8K HDR', 'natural dynamic range'],
    ['HDR', 'natural dynamic range'],
    ['ultra realistic', 'realistic'],
    ['cinematic realism', 'documentary photo realism'],
    ['cinematic', 'documentary'],
    ['flower fairy makeup', 'minimal botanical makeup'],
    ['flower fairy', 'botanical environment styling'],
    ['fairy makeup', 'minimal botanical makeup'],
    ['luminous pastel eye shimmer', 'subtle botanical surface color around the eyes, no fantasy-eye styling'],
    ['pastel eye shimmer', 'subtle botanical surface color around the eyes'],
    ['delicate botanical glow', 'subtle botanical color tint'],
    ['botanical glow', 'botanical color tint'],
    ['romantic fantasy freshness', 'ordinary real-person forest snapshot naturalness'],
    ['fantasy freshness', 'real-person naturalness'],
    ['professional travel photography', 'ordinary documentary travel photography'],
    ['travel photoshoot', 'travel snapshot'],
    ['photoshoot', 'snapshot'],
    ['photographic polish', 'photographic realism'],
    ['high-end', 'plain'],
    ['premium', 'natural'],
    ['ethereal glow', 'soft atmospheric light'],
    ['ethereal atmosphere', 'soft atmospheric depth'],
    ['ethereal particles', 'soft atmospheric light'],
    ['celestial particles', 'soft ambient light'],
    ['celestial radiance', 'soft ambient light'],
    ['celestial glow', 'soft ambient light'],
    ['celestial light', 'soft ambient light'],
    ['immortal realm glow', 'soft environmental glow'],
    ['divine radiance', 'warm environmental light'],
    ['xianxia ethereal', 'soft xianxia atmospheric'],
    ['premium fantasy editorial realism', 'documentary photo realism with real-person identity fidelity'],
    ['editorial realism', 'documentary photo realism'],
    ['magazine cover', 'real tourist documentary photography'],
    ['concept art quality', 'real-person photographic quality'],
    ['character concept art', 'real photograph of the uploaded person inside a designed environment'],
    ['fashion beauty portrait', 'controlled real-person portrait photography'],
    ['travel documentary', 'location-based real-person photography'],
    ['candid travel', 'grounded location-based real-person photography'],
    ['location editorial', 'location-based real tourist photography'],
    ['travel editorial', 'real tourist documentary photography'],
    ['low-key dramatic', 'controlled dramatic'],
  ],
  identitySafety: {
    mode: 'identity_sovereign',
    fantasyScope: ['environment', 'costume', 'props', 'lighting', 'atmosphere'],
    faceScope: 'preserve_only',
    riskFlags: [
      'beauty_template_risk',
      'archetype_face_risk',
      'editorial_beauty_risk',
      'dynamic_angle_identity_risk',
      'head_scale_risk',
      'makeup_restructure_risk',
    ],
  },
  lensOptions: [
    {
      id: 'l_50',
      name: '50mm 全身最穩',
      desc: 'Simulated 50mm full-body real travel photography lens: natural human-eye perspective, minimal distortion, realistic head-to-body proportions, safest for full-body costume, large skirts, robes, armor, and complete outfit display with stable full-body or three-quarter documentary framing.',
    },
  ],
  poseModes: [
    { id: 'scene_default', label: '場景預設', prompt: '' },
    { id: 'identity_front', label: '鎖臉正面', prompt: 'Identity-first front-facing pose: face directed toward camera, very slight body angle only, no head twist, no face obstruction.' },
    { id: 'micro_turn', label: '鎖臉微側', prompt: 'Identity-safe micro-turn: face remains mostly front-facing with only a subtle 10-15 degree head turn, shoulders may angle gently, facial geometry must remain readable.' },
    { id: 'three_quarter_body', label: '三分之四身', prompt: 'Three-quarter body documentary pose: upper body and costume visible, face open to camera, natural neck and shoulder alignment.' },
    { id: 'full_body_stable', label: '全身穩定', prompt: 'Stable full-body pose: head-to-toe visible, realistic head-to-body proportion, eye-level or chest-height camera, no forced perspective.' },
    { id: 'seated_safe', label: '安全坐姿', prompt: 'Identity-safe seated pose: graceful seated angle, torso supported, face clearly visible, hands below face line.' },
    { id: 'walking_safe', label: '緩步動作', prompt: 'Slow walking motion: grounded step, fabric movement, face still directed toward camera, no spin or jump.' },
    { id: 'prop_safe', label: '安全持物', prompt: 'Prop interaction pose: hands and prop stay below eye level or to the side, never covering eyes, nose, mouth, jawline, or facial outline.' },
    { id: 'bridal_soft', label: '婚紗柔和', prompt: 'Soft bridal pose: veil, bouquet, or gown interaction kept away from the face, romantic half-body or three-quarter framing, facial identity clean.' },
    { id: 'queen_command', label: '女王威儀', prompt: 'Commanding regal pose: stable torso, calm authority through posture, hand on throne, scepter, document, or architectural support, no exaggerated gesture.' },
  ],
  categoryRules: {
    ancientFullBody: {
      categories: ['xianxia', 'hanfu', 'oriental', 'myth', 'fantasy', 'water', 'drama', 'spirits', 'jinyong', 'chinese_story', 'dynasty_palace', 'classic_lit', 'china_drama'],
      lens: 'l_50',
      guidance: 'Ancient costume lens rule: prioritize 50mm for full robe, wide sleeves, hair ornaments, and head-to-body stability.',
    },
    balancedEditorial: {
      categories: ['queen', 'modern_lady', 'realistic_life', 'reference_styles', 'holy_angel', 'goddess_myth', 'fallen_angel', 'succubus_demon', 'darkfantasy', 'gothic'],
      lens: 'l_50',
      guidance: 'Balanced documentary lens rule: use 50mm to preserve head-to-body proportion while keeping face, outfit, and environment equally readable.',
    },
    characterStable: {
      categories: ['game', 'cos_character', 'cyberpunk_sf', 'wedding_diamond'],
      lens: 'l_50',
      guidance: 'Character and bridal lens rule: use 50mm to keep costume detail, full-body scale, and face readability stable in one frame.',
    },
    travelStable: {
      categories: ['taiwan_travel', 'europe_travel', 'japan_travel', 'korea_sea', 'world_travel', 'china_mark', 'mountain_sea', 'beast_tamer', 'dragon_beast'],
      lens: 'l_50',
      guidance: 'Travel lens rule: use 50mm for documentary location framing where the location, outfit, and body scale must stay readable.',
    },
  },
};
