// Prompt governance config v1.0.0
// Keep risk terms, lens policy, pose modes, and category-specific rules outside core prompt code.
window.PROMPT_GOVERNANCE = {
  antiPatterns: {
    bannedCameraLanguageIds: ['cl_movie', 'cl_travel'],
    bannedAngleIds: ['yang', 'huimou'],
    bannedPromptTerms: [
      'movie trailer',
      'blockbuster',
      'dramatic hero framing',
      'looking back over shoulder',
      'turn-back glance',
      'low angle upward shot',
      'low-angle',
      'perfect beauty',
      'flawless',
      'luxury beauty',
      'cat-eye',
      'heavy smoky eye',
      'extreme pose',
      'jumping',
      'spinning',
      'back-facing',
      'travel documentary',
      'vlog',
      'candid travel',
      'low-key dramatic',
      'ethereal atmosphere',
      'celestial mist',
      'arms overhead',
      'covering face',
      'oversized head',
      'chibi proportions',
    ],
  },
  replacements: [
    ['movie trailer camera language', 'controlled cinematic camera framing'],
    ['fashion editorial camera language', 'controlled fashion camera framing'],
    ['blockbuster visual language', 'natural cinematic visual language'],
    ['blockbuster', 'cinematic quality'],
    ['vlog', 'location editorial'],
    ['dramatic hero framing', 'stable cinematic framing'],
    ['looking back over shoulder', 'gentle three-quarter pause with face still readable'],
    ['turn-back glance', 'calm paused glance with face still readable'],
    ['low angle upward shot', 'stable eye-level or slight three-quarter shot'],
    ['low-angle', 'stable eye-level'],
    ['perfect beauty reconstruction', 'natural appearance'],
    ['perfect beauty', 'natural appearance'],
    ['flawless', 'natural'],
    ['luxury beauty enhancement', 'natural styling'],
    ['luxury beauty', 'natural styling'],
    ['goddess', 'regal figure'],
    ['heroine', 'central character'],
    ['celebrity', 'reference subject'],
    ['cat-eye liner reshaping', 'soft liner styling that follows the original eye shape'],
    ['cat-eye', 'soft liner'],
    ['heavy smoky eye', 'controlled smoky eye'],
    ['extreme pose', 'controlled pose'],
    ['jumping', 'grounded motion'],
    ['spinning', 'gentle movement'],
    ['back-facing', 'face-readable'],
    ['arms overhead', 'hands kept below eye level'],
    ['covering face', 'face unobstructed'],
    ['ethereal light', 'soft atmospheric light'],
    ['ethereal glow', 'soft atmospheric light'],
    ['ethereal atmosphere', 'soft atmospheric depth'],
    ['ethereal particles', 'soft atmospheric light'],
    ['celestial particles', 'soft ambient light'],
    ['celestial radiance', 'soft ambient light'],
    ['celestial glow', 'soft ambient light'],
    ['celestial light', 'soft ambient light'],
    ['immortal realm glow', 'soft environmental glow'],
    ['divine radiance', 'warm environmental light'],
    ['xianxia ethereal', 'soft xianxia atmospheric'],
    ['travel documentary', 'location editorial'],
    ['candid travel', 'grounded travel editorial'],
    ['low-key dramatic', 'controlled dramatic'],
  ],
  lensOptions: [
    {
      id: 'l_50',
      name: '50mm 全身最穩',
      desc: 'Simulated 50mm full-body fashion photography lens: natural human-eye perspective, minimal distortion, realistic head-to-body proportions, safest for full-body costume, large skirts, robes, armor, and complete outfit display with stable full-body or three-quarter editorial framing.',
    },
  ],
  poseModes: [
    { id: 'scene_default', label: '場景預設', prompt: '' },
    { id: 'identity_front', label: '鎖臉正面', prompt: 'Identity-first front-facing pose: face directed toward camera, very slight body angle only, no head twist, no face obstruction.' },
    { id: 'micro_turn', label: '鎖臉微側', prompt: 'Identity-safe micro-turn: face remains mostly front-facing with only a subtle 10-15 degree head turn, shoulders may angle gently, facial geometry must remain readable.' },
    { id: 'three_quarter_body', label: '三分之四身', prompt: 'Three-quarter body editorial pose: upper body and costume visible, face open to camera, natural neck and shoulder alignment.' },
    { id: 'full_body_stable', label: '全身穩定', prompt: 'Stable full-body pose: head-to-toe visible, realistic head-to-body proportion, eye-level or chest-height camera, no forced perspective.' },
    { id: 'seated_safe', label: '安全坐姿', prompt: 'Identity-safe seated pose: graceful seated angle, torso supported, face clearly visible, hands below face line.' },
    { id: 'walking_safe', label: '緩步動作', prompt: 'Slow walking motion: grounded step, fabric movement, face still directed toward camera, no spin or jump.' },
    { id: 'prop_safe', label: '安全持物', prompt: 'Prop interaction pose: hands and prop stay below eye level or to the side, never covering eyes, nose, mouth, jawline, or facial outline.' },
    { id: 'bridal_soft', label: '婚紗柔和', prompt: 'Soft bridal pose: veil, bouquet, or gown interaction kept away from the face, romantic half-body or three-quarter framing, facial identity clean.' },
    { id: 'queen_command', label: '女王威儀', prompt: 'Commanding regal pose: stable torso, calm authority through posture, hand on throne, scepter, document, or architectural support, no exaggerated gesture.' },
  ],
  categoryRules: {
    ancientFullBody: {
      categories: ['xianxia', 'hanfu', 'oriental', 'myth', 'fantasy', 'water', 'drama', 'spirits', 'jinyong', 'chinese_story', 'dynasty_palace', 'classic_lit', 'china_drama'],
      lens: 'l_50',
      guidance: 'Ancient costume lens rule: prioritize 50mm for full robe, wide sleeves, hair ornaments, and head-to-body stability.',
    },
    balancedEditorial: {
      categories: ['queen', 'modern_lady', 'realistic_life', 'reference_styles', 'holy_angel', 'goddess_myth', 'fallen_angel', 'succubus_demon', 'darkfantasy', 'gothic'],
      lens: 'l_50',
      guidance: 'Balanced editorial lens rule: use 50mm to preserve head-to-body proportion while keeping face, outfit, and environment equally readable.',
    },
    characterStable: {
      categories: ['game', 'cos_character', 'cyberpunk_sf', 'wedding_diamond'],
      lens: 'l_50',
      guidance: 'Character and bridal lens rule: use 50mm to keep costume detail, full-body scale, and face readability stable in one frame.',
    },
    travelStable: {
      categories: ['taiwan_travel', 'europe_travel', 'japan_travel', 'korea_sea', 'world_travel', 'china_mark', 'mountain_sea', 'beast_tamer', 'dragon_beast'],
      lens: 'l_50',
      guidance: 'Travel lens rule: use 50mm for environmental editorial framing where the location, outfit, and body scale must stay readable.',
    },
  },
};
