import fs from 'node:fs';
import path from 'node:path';
import {
  DISPLAYABLE_STATUSES,
  HTML_PATH,
  INDEX_DRAFT_PATH,
  INDEX_PATH,
  ROOT,
  THEME_BY_ID,
  entrySort,
  flattenUiEntries,
  loadProjectData,
  parseCodeValue,
  readJson,
  writeJson,
} from './lib/style_library.mjs';

const args = new Set(process.argv.slice(2));
const writeHtml = args.has('--write-html');
const useFormal = args.has('--formal');
const includeReview = args.has('--include-review');
const indexPath = useFormal && fs.existsSync(INDEX_PATH) ? INDEX_PATH : INDEX_DRAFT_PATH;
const generatedJsonPath = path.join(ROOT, 'dist', 'style-data.generated.json');
const generatedJsPath = path.join(ROOT, 'dist', 'style-data.generated.js');

const index = readJson(indexPath);
const { html, uiCats, cards } = loadProjectData();
const uiEntries = flattenUiEntries(uiCats);
const indexByRuntimeId = new Map(index.entries.map((entry) => [entry.runtime_id || entry.id, entry]));
const cardsById = new Map(cards.filter((card) => card.id).map((card) => [card.id, card]));

const displayStatuses = new Set(DISPLAYABLE_STATUSES);
if (includeReview) displayStatuses.add('review');

const rebuiltCats = uiCats.map((cat) => {
  const themeMeta = index.themes?.find((theme) => theme.id === cat.id) || THEME_BY_ID[cat.id] || {};
  const entries = (cat.entries || [])
    .map((entry) => {
      const indexEntry = indexByRuntimeId.get(entry.id);
      if (!indexEntry) {
        if (!includeReview) return null;
        return { ...entry, series: entry.sub || '待審', ui_status: 'review', sort_weight: 8999, risk_flags: ['missing_index'] };
      }
      if (!displayStatuses.has(indexEntry.ui_status)) return null;
      const sourceCard = cardsById.get(indexEntry.source_id || indexEntry.id);
      return {
        ...entry,
        ...runtimeFieldsFromCard(sourceCard),
        sub: entry.sub || indexEntry.display_sub || indexEntry.series,
        series: indexEntry.series,
        ui_status: indexEntry.ui_status,
        sort_weight: indexEntry.sort_weight,
        source_type: indexEntry.source_type,
        source_batch: indexEntry.source_batch,
        risk_flags: indexEntry.risk_flags || [],
      };
    })
    .filter(Boolean)
    .sort(entrySort);

  return {
    ...cat,
    name: themeMeta.name || cat.name,
    shortName: themeMeta.short_name || themeMeta.shortName || cat.name,
    series_order: themeMeta.series_order || [],
    entries,
  };
});

const visibleEntryIds = new Set(rebuiltCats.flatMap((cat) => cat.entries.map((entry) => entry.id)));
const indexVisibleButMissingRuntime = index.entries
  .filter((entry) => displayStatuses.has(entry.ui_status) && !visibleEntryIds.has(entry.runtime_id || entry.id))
  .map((entry) => ({
    id: entry.id,
    runtime_id: entry.runtime_id || entry.id,
    title: entry.title,
    theme_id: entry.theme_id,
    ui_status: entry.ui_status,
    reason: 'index-visible-but-not-in-current-runtime-cats',
  }));

writeJson(generatedJsonPath, {
  meta: {
    generated_at: new Date().toISOString(),
    index_path: path.relative(ROOT, indexPath),
    source: 'index.html CATS + 風格索引草案 metadata',
    write_html: writeHtml,
  },
  cats: rebuiltCats,
  diagnostics: {
    ui_entries_before: uiEntries.length,
    ui_entries_after: rebuiltCats.reduce((sum, cat) => sum + cat.entries.length, 0),
    index_visible_but_missing_runtime: indexVisibleButMissingRuntime,
  },
});

const js = [
  '// Generated by scripts/build_style_data.mjs',
  `// Generated at ${new Date().toISOString()}`,
  `window.HONGBING_STYLE_CATS = ${JSON.stringify(rebuiltCats, null, 2)};`,
  '',
].join('\n');
fs.mkdirSync(path.dirname(generatedJsPath), { recursive: true });
fs.writeFileSync(generatedJsPath, js, 'utf8');

let wroteHtml = false;
if (writeHtml) {
  if (!/const CATS = [\s\S]*?;\s*let curCatID/.test(html)) {
    throw new Error('Failed to find CATS block in index.html');
  }
  const nextHtml = html.replace(
    /const CATS = [\s\S]*?;\s*let curCatID/,
    `const CATS = ${JSON.stringify(rebuiltCats, null, 2)};\n\nlet curCatID`
  );
  if (nextHtml !== html) {
    fs.writeFileSync(HTML_PATH, nextHtml, 'utf8');
    wroteHtml = true;
  }
}

console.log(JSON.stringify({
  indexPath,
  cats: rebuiltCats.length,
  uiEntriesBefore: uiEntries.length,
  uiEntriesAfter: rebuiltCats.reduce((sum, cat) => sum + cat.entries.length, 0),
  indexVisibleButMissingRuntime: indexVisibleButMissingRuntime.length,
  generatedJsonPath,
  generatedJsPath,
  wroteHtml,
}, null, 2));

function runtimeFieldsFromCard(card) {
  if (!card) return {};
  const fields = card.fields || {};
  const runtime = {};
  assignText(runtime, 'mk', parseCodeValue(fields['妝容']));
  assignText(runtime, 'scene', fields['場景背景']);
  assignText(runtime, 'outfit', fields['服裝']);
  assignText(runtime, 'prop', fields['動作與鏡頭']);
  assignText(runtime, 'comp', fields['構圖']);
  assignText(runtime, 'fx', fields['特效']);
  assignText(runtime, 'tone', fields['色調']);
  assignText(runtime, 'ang', parseCodeValue(fields['鏡頭角度']));
  assignText(runtime, 'ratio', parseCodeValue(fields['圖片比例']));
  assignText(runtime, 'lens', parseCodeValue(fields['鏡頭焦段']) || 'l_50');
  assignText(runtime, 'light', parseCodeValue(fields['燈光風格']));
  assignText(runtime, 'atm', parseCodeValue(fields['整體氛圍']));
  assignText(runtime, 'camLang', parseCodeValue(fields['鏡頭語言']));
  return runtime;
}

function assignText(target, key, value) {
  const text = String(value || '').trim();
  if (text) target[key] = text;
}
